export type BeginnerStep = { where: string; actions: string[]; expected: string };
export const beginnerSteps: Record<string, BeginnerStep> = {
  start: { where: 'Dentro del escritorio de práctica, en la esquina inferior izquierda. Inicio es el botón con cuatro cuadros azules.', actions: ['Mueve la flecha del ratón sobre los cuatro cuadros.', 'Presiona y suelta una sola vez el botón izquierdo del ratón.'], expected: 'Aparecerá un recuadro con Buscar aplicaciones. Para poder escribir, pulsa Siguiente paso debajo del simulador.' },
  'search-word': { where: 'En el menú abierto, localiza el cuadro blanco debajo de Buscar aplicaciones.', actions: ['Haz un clic dentro del cuadro blanco.', 'Escribe Word con el teclado, sin comillas. Si te equivocas, usa Retroceso para borrar.', 'Haz un clic en Buscar, junto a la lupa; también puedes pulsar Enter.'], expected: 'Verás la confirmación debajo del simulador. Pulsa Siguiente paso para mostrar los resultados de la búsqueda.' },
  word: { where: 'En el menú, debajo de Mejor coincidencia. Word aparece con un icono azul que tiene una W.', actions: ['Busca la fila que dice Word y Aplicación.', 'Haz un solo clic en esa fila; aquí no se necesita doble clic.'], expected: 'Se abrirá una ventana simulada de Word. Después pulsa Terminar debajo del escritorio; no necesitas crear un documento todavía.' },
  blank: { where: 'A la derecha del menú azul, en la tarjeta Documento en blanco.', actions: ['Lee el nombre de la tarjeta para distinguirla de Carta sencilla.', 'Haz un solo clic en Documento en blanco.'], expected: 'Verás un aviso verde que confirma tu elección. En esta práctica solo eliges cómo empezar: todavía no escribes. Pulsa Siguiente paso para probar una situación distinta.' },
  template: { where: 'A la derecha del menú azul, en la tarjeta Carta sencilla. Una plantilla es un modelo de documento con un diseño preparado.', actions: ['Localiza la tarjeta Carta sencilla.', 'Haz un clic en ella. No elijas Documento en blanco: ahora necesitas un modelo.'], expected: 'Aparecerá el aviso de plantilla lista. No tienes que rellenarla aquí. Pulsa Siguiente paso para aprender a recuperar un archivo.' },
  open: { where: 'En la columna azul de la izquierda, debajo de Inicio y Nuevo, está Abrir.', actions: ['Busca la palabra Abrir en esa columna.', 'Haz un solo clic en Abrir.'], expected: 'Verás el aviso de buscador de archivos abierto. Pulsa Siguiente paso: entonces aparecerá la lista de archivos de ejemplo.' },
  'file-practica': { where: 'En la lista de archivos, busca el nombre completo Mi práctica.docx. La terminación .docx identifica este documento de Word.', actions: ['Lee los tres nombres. No tienes que buscar archivos en tu computadora.', 'Haz un clic en Mi práctica.docx; no elijas Lectura.pdf ni Presupuesto.xlsx.'], expected: 'Un aviso confirmará que elegiste el documento correcto. Pulsa Terminar debajo del simulador.' },
  title: { where: 'En la parte más alta de la ventana simulada, la franja azul dice Mi práctica.docx — Word.', actions: ['Busca esa franja azul.', 'Haz un solo clic sobre el nombre del documento.'], expected: 'Se confirmará que reconociste la barra de título. Su función es mostrar qué documento está abierto; no tienes que cambiar su nombre. Pulsa Siguiente paso.' },
  tabs: { where: 'Justo debajo de la franja azul está la fila Archivo, Inicio, Insertar, Diseño, Disposición, Revisar y Vista.', actions: ['Localiza esa fila de nombres; cada pestaña agrupa herramientas.', 'Haz un clic en cualquier parte de esa fila. Aquí se identifica la fila completa, no una pestaña individual.'], expected: 'Se confirmará que identificaste las pestañas. No se abrirá otro menú en este ejercicio. Pulsa Siguiente paso.' },
  ribbon: { where: 'Debajo de las pestañas está la franja con Pegar, Aptos, 12, N, K, S y otras herramientas. Se llama cinta de opciones.', actions: ['Distingue la fila de nombres de la franja de herramientas que está debajo.', 'Haz un clic dentro de la franja de herramientas.'], expected: 'Se confirmará que localizaste la cinta. No aplicarás formato todavía: solo identificarás su ubicación. Pulsa Siguiente paso.' },
  page: { where: 'En el centro aparece una hoja blanca con el título Mi primer documento. Es el área del documento.', actions: ['Busca la hoja blanca, no el fondo gris que la rodea.', 'Haz un clic dentro de la hoja. No escribas: este ejercicio solo reconoce la zona.'], expected: 'Se confirmará que localizaste el espacio donde se escribe en Word. Pulsa Siguiente paso.' },
  status: { where: 'En la parte inferior izquierda de la ventana, debajo de la hoja, está Página 1 de 1 · 23 palabras.', actions: ['Baja la mirada hasta esa información dentro de la ventana simulada.', 'Haz un clic en el texto de páginas y palabras.'], expected: 'Se confirmará que encontraste la barra de estado. Estos números son datos de ejemplo. Pulsa Siguiente paso.' },
  zoom: { where: 'En la esquina inferior derecha están los signos − y + y el porcentaje 100 %. Ese conjunto es el control de zoom.', actions: ['Busca el porcentaje 100 % dentro de la ventana de Word.', 'Haz un clic en esa zona. Aquí solo la identificas: no arrastres el control.'], expected: 'Se confirmará que reconociste el zoom. En Word permite ver la hoja más cerca o más lejos, sin cambiar el tamaño real de las letras. Pulsa Terminar.' },
};

export const lessonPreparation: Record<string, string> = {
  'word-start': 'Word es un programa para escribir documentos. El escritorio es la pantalla de fondo con iconos; un icono es una imagen pequeña que representa un programa. Primero puedes explorar tres formas de abrirlo sin nota. Después practicarás la ruta Inicio → búsqueda → Word, que es la que se evalúa en esta lección.',
  'word-create': 'Un documento es el trabajo que elaboras en Word. Puedes empezar con una hoja en blanco, usar una plantilla (un modelo con diseño preparado) o abrir un archivo ya guardado. Cada paso plantea una situación diferente. El simulador confirma tus elecciones con mensajes: todavía no es un editor para escribir o guardar archivos.',
  'word-interface': 'La interfaz es el conjunto de zonas y herramientas que ves en la ventana de Word. En esta lección solo debes señalar esas zonas con un clic. No se escribe, no se cambia el formato y no se mueve el zoom. Primero conocerás cada zona con ayuda y después identificarás su función sin el resaltado.',
};
