export type WordFact = { id: string; lessonId: string; title: string; fact: string; example: string; sourceTitle: string; sourceUrl: string };
export const wordFacts: WordFact[] = [
  { id: 'recent', lessonId: 'word-start', title: 'No siempre tienes que buscar tu archivo desde cero', fact: 'Al iniciar Word puedes encontrar una lista de documentos usados recientemente. Si el archivo no aparece, puedes buscarlo con Abrir.', example: 'Si ayer trabajaste en una carta, su nombre podría aparecer en Recientes. Esa lista te ayuda a encontrarla; no significa que se haya creado otra copia.', sourceTitle: 'Microsoft: tareas básicas en Word', sourceUrl: 'https://support.microsoft.com/es-es/word/basic-tasks-in-word' },
  { id: 'templates', lessonId: 'word-create', title: 'Una plantilla te da un punto de partida', fact: 'Una plantilla es un modelo con diseño y estilos preparados. Puedes agregar tu contenido sin tener que diseñar todo desde una hoja en blanco.', example: 'Una plantilla de carta puede darte una estructura inicial. Tú escribes el destinatario y tu mensaje: elegirla no hace que el trabajo ya esté terminado.', sourceTitle: 'Microsoft: empezar un documento', sourceUrl: 'https://support.microsoft.com/es-es/word/basic-tasks-in-word' },
  { id: 'count', lessonId: 'word-interface', title: 'Word puede contar las palabras por ti', fact: 'Word cuenta las palabras mientras escribes. En Word para Windows, pulsar el contador de la barra de estado permite consultar también datos como caracteres, párrafos y líneas.', example: 'Si una tarea pide 200 palabras, el contador te ayuda a comprobar la extensión. Una palabra no es lo mismo que un carácter: los caracteres incluyen las letras.', sourceTitle: 'Microsoft: mostrar recuento de palabras', sourceUrl: 'https://support.microsoft.com/es-ES/Word/training/show-word-count' },
  { id: 'zoom', lessonId: 'word-interface', title: 'Acercar la vista no agranda las letras del documento', fact: 'El zoom cambia qué tan cerca ves la página en pantalla. No es lo mismo que cambiar el tamaño de la letra con las herramientas de formato.', example: 'Al pasar de 100 % a 150 % de zoom, ves el contenido más grande. Si la letra era de tamaño 12, sigue siendo de tamaño 12.', sourceTitle: 'Microsoft: acercar o alejar un documento', sourceUrl: 'https://support.microsoft.com/es-es/office/acercar-o-alejar-un-documento-0a0ebbed-10e7-444b-b16b-6f0c090f8ec7' },
];
export function factsForLesson(lessonId: string, phase: string) {
  return phase === 'read' ? wordFacts.filter(fact => fact.lessonId === lessonId) : [];
}
